ci: don't build two times

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -67,6 +67,28 @@ jobs:
 
       - name: Install dependencies
         run: npm ci
+      
+      - name: Patch boring-sys2 on Windows
+        if: runner.os == 'Windows'
+        shell: bash
+        run: |
+          cd rust
+          
+          cargo fetch
+
+          FILE=$(find ~/.cargo/registry/src -name "main.rs" | grep "boring-sys2" | grep "build")
+          
+          if [ -z "$FILE" ]; then
+            echo "Error: Could not find boring-sys2 build/main.rs to patch"
+            exit 1
+          fi
+          
+          echo "Patching $FILE"
+
+          sed -i 's/let bssl_dir = built_boring_source_path(config);/let bssl_dir = built_boring_source_path(config); if config.target.ends_with("-msvc") { println!("cargo:rustc-link-search=native={}\/lib", bssl_dir.display()); }/' "$FILE"
+
+          sed -i 's/cfg.build_target("ssl").build();/\/\/ cfg.build_target("ssl").build();/' "$FILE"
+          sed -i 's/cfg.build_target("crypto").build()/cfg.build_target("ALL_BUILD").build()/' "$FILE"
 
       - name: Build native module (x86_64 musl target)
         if: matrix.settings.target == 'x86_64-unknown-linux-musl'
